### ISSUE TITLE
How do I install this thing?

### ISSUE THREAD

**Issue by CodyMarkix** [Mjtlittle/PyDatapack#1]
There doesn't seem to be any way to install this. At least there's no way shown in README.md

**Comment by Mjtlittle** [comment]
Hey, I haven't touched this code in a long time, and I never uploaded it to pypi as it was never finished. Currently the only way to play with it would be to clone the repo.

However, if you are familiar with Nodejs or javascript/typescript; I found this package a while ago that is still being supported. It looks really well made, and Ive been meaning to try it out.
https://www.sandstone.dev/

**Comment by CodyMarkix** [comment]
Hi, I have also noticed some other wrappers for Javascript, but me being confident in Python and rather lacking skills in Javascript to attempt something like writing a datapack in it brought me to your repository.

Thank you for dropping the link though! Perhaps I'll try it some time soon.
